#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -e

# --- User Input ---
DEFAULT_LOCALE="en_US.UTF-8"
read -p "Enter the desired locale [default: $DEFAULT_LOCALE]: " SELECTED_LOCALE
# Use default if input is empty
SELECTED_LOCALE=${SELECTED_LOCALE:-$DEFAULT_LOCALE}

# Validate locale format (basic check)
if ! [[ "$SELECTED_LOCALE" =~ ^[a-z]{2}_[A-Z]{2}\.UTF-8$ ]]; then
    echo "--- Invalid locale format. Please use format like 'en_US.UTF-8'. Exiting."
    exit 1
fi

echo "--- Starting Locale Setup for $SELECTED_LOCALE ---"

# --- Install Locales Package ---
echo "--- Ensuring 'locales' package is installed..."
sudo apt update
sudo apt install -y locales

# --- Generate Locale ---
# Check if locale is already generated by checking output of locale -a
if ! locale -a | grep -q "^${SELECTED_LOCALE%.*}\\.${SELECTED_LOCALE##*.}"; then
    echo "--- Generating locale '$SELECTED_LOCALE'..."
    # Add locale to /etc/locale.gen if not present
    if ! grep -q "^${SELECTED_LOCALE} UTF-8" /etc/locale.gen; then
        echo "${SELECTED_LOCALE} UTF-8" | sudo tee -a /etc/locale.gen > /dev/null
    fi
    sudo locale-gen "$SELECTED_LOCALE"
else
    echo "--- Locale '$SELECTED_LOCALE' already generated."
fi


# --- Set System Locale ---
echo "--- Setting system-wide locale to '$SELECTED_LOCALE'..."
sudo update-locale LANG="$SELECTED_LOCALE" LC_ALL="$SELECTED_LOCALE"

# --- Display Final Settings ---
echo "--- Current locale settings:"
locale


echo
echo "--- Locale Setup Complete ---"
echo "System locale set to $SELECTED_LOCALE. A system reboot might be required for all applications to pick up the change."
echo
exit 0
